### ISSUE TITLE
Error in proxy2 when scrapping

### ISSUE THREAD

**Issue by asraelvudogel** [leoncvlt/blinkist-scraper#44]
I'm getting constant errors when scraping even on the start, when it's connecting and downloading the booklist. The message is allways the same but it happens multiple times nearly once per second.

> Error making request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/seleniumwire/proxy/proxy2.py", line 91, in proxy_request
>     conn.request(self.command, path, req_body, dict(req.headers))
>   File "/usr/lib/python3.7/http/client.py", line 1260, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib/python3.7/http/client.py", line 1306, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.7/http/client.py", line 1255, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.7/http/client.py", line 1030, in _send_output
>     self.send(msg)
>   File "/usr/lib/python3.7/http/client.py", line 970, in send
>     self.connect()
>   File "/usr/local/lib/python3.7/dist-packages/seleniumwire/proxy/proxy2.py", line 368, in connect
>     super().connect()
>   File "/usr/lib/python3.7/http/client.py", line 1415, in connect
>     super().connect()
>   File "/usr/lib/python3.7/http/client.py", line 942, in connect
>     (self.host,self.port), self.timeout, self.source_address)
>   File "/usr/lib/python3.7/socket.py", line 707, in create_connection
>     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
>   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -2] Name or service not known

Scraping works as asprected but I can't find, what causes this error. It's not depending on any of the possible arguments.

**Comment by asraelvudogel** [comment]
After a lot of searching, I found out the the Adblock-feature in my router causes this error, so I closed this issue.
