### ISSUE TITLE
Script Throws Exception for audio download of blinks

### ISSUE THREAD

**Issue by girishbaviskar** [leoncvlt/blinkist-scraper#54]
Hello there,
I recently discovered this repository and started using. I'm trying to download the audio blinks, but I keep getting the following exception.
Is there something I'm missing here, or is this for everyone?
Please advise what I can do to prevent this error.

```
$ python blinkistscraper --language en --match-language --audio myEmail myPassword
[15:41:38] INFO Starting scrape run...
[15:41:39] INFO Initialising chromedriver at C:\Users\Girish\AppData\Local\Programs\Python\Python37\lib\site-packages\chromedriver_autoinstaller\90\chromedriver.exe...
[15:41:48] ERROR Timeout waiting for ublock config overwrite alert
[15:42:03] INFO Logged into Blinkist. Loading Library...
[15:42:07] INFO Scraping categories: Entrepreneurship, Politics, Marketing & Sales, Science, Health & Nutrition, Personal Development, Economics, History, Communication Skills, Corporate Culture, Management & Leadership, Motivation & Inspiration, Money & Investments, Psychology, Productivity, Sex & Relationships, Technology & the Future, Mindfulness & Happiness, Parenting, Society & Culture, Nature & the Environment, Biography & Memoir, Career & Success, Education, Religion & Spirituality, Creativity, Philosophy
[15:42:07] INFO Getting all books for category Entrepreneurship...
[15:42:13] INFO Found 198 books
[15:42:13] ERROR requests
Traceback (most recent call last):
  File "blinkistscraper\__main__.py", line 412, in <module>
    main()
  File "blinkistscraper\__main__.py", line 373, in main
    match_language=match_language,
  File "blinkistscraper\__main__.py", line 258, in scrape_book
    driver, book_json, args.language
  File "blinkistscraper\scraper.py", line 504, in scrape_book_audio
    del driver.requests
AttributeError: requests
[15:42:13] CRITICAL Uncaught Exception. Exiting...


```

**Comment by circark** [comment]
hello

i'm having the exact same issue.
PDF/HTML scrapping works fine, but --audio not.

**Comment by hello070707-byte** [comment]
Try python- https://medium.com/@manrajsinghglobal/i-automated-my-entire-web-scraping-workflow-from-ticket-creation-to-pull-request-58653ed79bbd
