### ISSUE TITLE
blinkist-scraper no longer working - attribute error!?

### ISSUE THREAD

**Issue by 3mfg** [leoncvlt/blinkist-scraper#57]
Dear Leonardo, *

great script - used to backup some of my favorite books in January as epub and mp4. Worked like a charm.
Now it **breaks shortly after initialising** the (already updated) **chromedriver**:

> C:\blinkistscraper>python main.py <username> <pwd> --books.txt --cooldown 5 --concat-audio --keep-noncat --save-cover --embed-cover-art
> ←[2m[13:10:21]←[0m ←[34mINFO←[0m Starting scrape run...
> ←[2m[13:10:22]←[0m ←[34mINFO←[0m Initialising chromedriver at <path> ~\Python\Python38\lib\site-packages\chromedriver_autoinstaller\91\chromedriver.exe...
> 
> DevTools listening on ws://~
> ←[2m[13:10:52]←[0m ←[34mINFO←[0m Logged into Blinkist. Loading Library...
> 
> 
> Traceback (most recent call last):
>   File "main.py", line 340, in <module>
>     main()
>   File "main.py", line 303, in main
>     dump_exists = scrape_book(
>   File "main.py", line 217, in scrape_book
>     audio_files = scraper.scrape_book_audio(
>   File "~\scraper.py", line 504, in scrape_book_audio
>     del driver.requests
> AttributeError: requests

**Any(body) an idea what's the root cause resp. how to fix?**
Thanks in advance!

**Comment by kotobuki09** [comment]
Download audiobook is breaking for me. I only can download the epub version. Hope that the owner will update the script soon so I can back up all the library.

**Comment by 3mfg** [comment]
> Download audiobook is breaking for me. I only can download the epub version. Hope that the owner will update the script soon so I can back up all the library.

interesting - how exactly do you manage to download the epub version?
. which command line parameters are you using?
. which code module versions? which modifications?
Thanks in advance for the info!

**Comment by kotobuki09** [comment]
https://github.com/leoncvlt/blinkist-scraper/issues/46#issuecomment-878762285
This one working really great for me so far!! 

I use the latest version with some modifications mention in the post above.
python blinkistscraper USER PASSWORD --create-pdf --no-ublock --language en --match-language

**Comment by 3mfg** [comment]
which modifications resp. which post are you referring to exactly?
Thanks for the info, kotobuki09

**Comment by kotobuki09** [comment]
For only downloading ebook. I think this is a better solution https://github.com/leoncvlt/blinkist-scraper/issues/46#issuecomment-827099491

This is for everything including audiobooks as well.
https://github.com/leoncvlt/blinkist-scraper/issues/46#issuecomment-878762285
You did reading what I quote over here right?
Change line 180 in scraper.py to allow time to manually install extension: WebDriverWait(driver, 60) --> WebDriverWait(driver, 360)
